spring.application.name=JobPortalSystem
spring.datasource.url=jdbc:mysql://localhost:3306/JobPortalSystem
spring.datasource.username=root
spring.datasource.password=Rahul@666
spring.jpa.hibernate.ddl-auto=update


